"""Chapter 3 — Hardware and System Implementation."""


def chapter_3(rep):
    rep.h1("3. Hardware and System Implementation")

    # ------------------------------------------------------------------
    rep.h2("3.1 Cartesian Motion System")

    rep.h3("3.1.1 Motors and drivers")
    rep.p(
        "Three NEMA17 stepper motors move the gantry: two frame-mounted motors driving the "
        "CoreXY belt path, and one motor on the moving carriage driving Z. A fourth NEMA17 "
        "drives the feeder belt and belongs to the Uno and not to the gantry. Each of the "
        "three gantry motors has its own TB6600 driver, and each TB6600 takes a direction pulse "
        "and a step pulse from the Mega.")
    rep.table(
        "Motor and driver inventory.",
        ["Motor", "Type", "Driver", "Controller", "Drives"],
        [
            ["Motor 1", "NEMA17, 1.8 deg/step (200 steps/rev)", "TB6600", "Arduino MEGA",
             "CoreXY belt, one of the coupled pair"],
            ["Motor 2", "NEMA17, 1.8 deg/step", "TB6600", "Arduino MEGA",
             "CoreXY belt, the other of the pair"],
            ["Motor 3", "NEMA17, 1.8 deg/step", "TB6600", "Arduino MEGA",
             "Z axis, independent of X/Y"],
            ["Motor 4", "NEMA17, 1.8 deg/step", "A4988", "Arduino Uno", "Feeder conveyor belt"],
            ["Rotation", "28BYJ-48, 5 V, 2,048 steps per output revolution", "ULN2003",
             "Arduino MEGA", "90-degree claw rotation"],
            ["Gripper", "Hobby servo", "direct PWM", "Arduino MEGA", "Claw jaws, OPEN / CLOSE"],
            ["Container gate", "Hobby servo", "direct PWM", "Arduino Uno",
             "Two-stage hopper gate"],
            ["Aligner", "Hobby servo", "direct PWM", "Arduino Uno", "Squares the staged block"],
        ],
        widths=[2.2, 4.6, 1.8, 2.6, 3.8], size=9)
    rep.p(
        "The full motor electrical specification is "
        "[[VALUE NEEDED: NEMA17 holding torque (N.cm) and rated phase current (A) for the "
        "motors actually fitted]], and the driver current limits are set to "
        "[[VALUE NEEDED: the Vref / current limit set on each TB6600 and on the A4988]]. The "
        "microstepping is not recorded anywhere in the repository either, but it can be "
        "recovered from the calibration with some confidence, and doing so is worth the space "
        "because it is the one place where the machine's software constants and its physical "
        "transmission can be checked against each other.")
    rep.p(
        "The firmware records X as 4,550 steps over 22.8 cm and Y as 7,600 steps over 38.0 cm, "
        "which is 199.56 and 200.00 steps/cm. A 20-tooth GT2 pulley advances 40 mm per "
        "revolution, so a 200 step/rev motor at quarter-step microstepping gives 800 steps per "
        "revolution, which is exactly 20 steps/mm, or 200 steps/cm. Y agrees to four "
        "significant figures and X to 0.2 %. Z is recorded as 1,350 steps over 26.5 cm, which is "
        "50.94 steps/cm, and the same 20-tooth pulley at **full step** gives 50.0 steps/cm. "
        "{{INFERRED: X/Y TB6600s at 1/4 microstepping and the Z TB6600 at full step, with 20-tooth "
        "GT2 pulleys throughout. Deduced from the step calibration; the driver DIP switches were "
        "never written down. Confirm against the switch settings on each driver.}}")
    rep.note(
        "The 1.9 % gap on Z is worth a note rather than a shrug. At 5.0 steps/mm exactly, "
        "1,350 steps is 27.0 cm, while the firmware carries a tape-measured 26.5 cm. Either the "
        "tape measurement is 5 mm short or the transmission is not quite what the arithmetic "
        "above assumes. The firmware measures the real switch-to-switch step distance on any run "
        "that starts from a true zero and prints it next to the constant for exactly this "
        "reason, so the check is one `0+` command followed by one `5` report.")

    rep.h3("3.1.2 Step generation and motion tuning")
    rep.p(
        "Motion is generated by a fixed-period pulse loop with no acceleration ramp at all. A "
        "move of N steps toggles the step pin N times with a fixed half-period between edges, "
        "so a move takes N times the step period and that is genuinely computable and not "
        "estimated. X and Y are tuned separately from Z, because Z lifts against gravity and, "
        "once a block is gripped, against a load.")
    rep.table(
        "Motion tuning constants, from the live firmware.",
        ["Constant", "Value", "Meaning"],
        [
            ["`STEP_DELAY`", "575 us", "Half-period for X and Y: 1.15 ms per step, 870 steps/s, "
                                       "about 4.36 cm/s at 199.56 steps/cm."],
            ["`STEP_DELAY_Z`", "950 us", "Half-period for Z: 1.9 ms per step, 526 steps/s, about "
                                         "10.3 mm/s."],
            ["`stepsPerMove`", "150 steps", "One manual X/Y jog, about 0.75 cm."],
            ["`stepsPerMoveZ`", "150 steps", "One manual Z jog, about 2.9 cm."],
            ["`DIR_SETTLE_MS`", "5 ms", "Settle after changing a direction pin before the first "
                                        "pulse."],
            ["`LIMIT_CONFIRM_US`", "200 us", "How long a switch must read active before it is "
                                             "believed."],
            ["`LIMIT_CHECK_EVERY_N_STEPS`", "1", "Every switch is polled on every step."],
        ],
        widths=[4.6, 2.4, 8.0], size=9)
    rep.p(
        "The absence of an acceleration ramp is a deliberate trade rather than an omission. It "
        "costs top speed and it is harder on the mechanics at a direction reversal, and in "
        "exchange it makes every move's duration exactly predictable from its step count. That "
        "is what lets the firmware put its own predicted duration on the wire as `ms=` for every "
        "Z move (Section 4.1.2), which in turn is what lets the browser's digital twin animate a "
        "descent against the machine's own arithmetic instead of against a timer someone chose. "
        "Section 5.2.3 measures how good that prediction actually is.")

    rep.h3("3.1.3 Homing and limit hardware")
    rep.p(
        "There are four limit switches, all plain micro switches, all wired normally closed and "
        "read through the AVR's internal pull-ups. Every switch is described in one table in the "
        "firmware by which **end of which axis** it guards, which is what lets Z carry two of "
        "them without any special-case code.")
    rep.table(
        "Limit switches.",
        ["Switch", "Pin", "Wiring", "Role", "What tripping it does"],
        [
            ["X", "30", "NC", "Home / zero for X",
             "Re-zeroes X. This is the X+ end; X then runs 0 to -4,550 steps."],
            ["Y", "31", "NC", "Home / zero for Y",
             "Re-zeroes Y. This is the Y- end; Y then runs 0 to +7,600 steps."],
            ["Z bottom", "28", "NC", "Home / zero for Z, and the GROUND reference",
             "Re-zeroes Z. Every stack level is measured from here."],
            ["Z top", "29", "NC", "Far-end stop for Z",
             "Stops the axis and reports where the top is. It does **not** redefine zero."],
        ],
        widths=[2.0, 1.2, 1.4, 4.4, 6.0], size=9)
    rep.p(
        "Homing drives an axis into its own switch in 200-step chunks, with the switch re-checked "
        "on every step, and gives up if the axis has travelled more than twice its software "
        "travel plus 500 steps of slack, which is derived from the travel cap and not "
        "hard-coded so that re-tuning a cap cannot leave a stale homing limit behind. **Home is "
        "the corner where both the X and the Y switch are pressed**, and that corner is machine "
        "position (0, 0). The `0` command homes X and Y; `0+` additionally drives Z to its "
        "bottom switch and then seeks its top switch, which puts the whole rig into a known "
        "state and, on the way, measures the real switch-to-switch Z distance.")
    rep.p(
        "The important operational property is that **the go-to sequence re-homes every time**: "
        "home Y into its switch, home X into its switch, then move Y to the target row and X to "
        "the target column. A single move costs a full return to the origin, and in "
        "exchange no step error can survive from one move to the next. On an open-loop machine "
        "with no encoders that is the whole of the position-integrity story, and Section 5.2 shows what "
        "it costs in cycle time.")

    rep.h3("3.1.4 Software limits")
    rep.p(
        "X and Y are capped in software at the far end of their travel, because there is no "
        "switch there: X at 4,550 steps from its switch, Y at 7,600. A soft limit only ever "
        "guards the end an axis travels **toward**, which is always the end away from its home "
        "switch, so by construction there is exactly one per axis. Z has no software limit at "
        "all any more; its far end is the physical switch on pin 29, and the 1,350-step constant "
        "survives only as the calibration number that converts steps to centimetres. Getting "
        "that number wrong no longer risks a crash, because the switch stops the axis either "
        "way; it only skews the scale, which shows up as blocks landing slightly high or low.")

    # ------------------------------------------------------------------
    rep.h2("3.2 End-Effector and Manipulation System")

    rep.h3("3.2.1 The gripper")
    rep.defs([
        ("What it does", "Holds one block through the carry, the traverse and the descent, and "
                         "releases it on command."),
        ("Inputs", "One PWM channel on Mega pin 6. Two commanded positions only: `O` opens to 0 "
                   "degrees, `C` closes to 54 degrees. `V <angle>` sets an arbitrary angle from "
                   "0 to 180 for bench work."),
        ("Outputs", "None. The servo is commanded and forgotten; nothing reports when the jaws "
                    "have arrived."),
        ("Typical workflow", "Inside a build the jaws open at phase 4 while the claw is still "
                             "clear above the feeder, close at phase 6 once Z is on the ground "
                             "switch, and open again at phase 11 once Z is at the target level."),
        ("Validation and constraints", "Because nothing reports arrival, every open and close "
                                       "inside a build is followed by a fixed 600 ms settle "
                                       "before Z is allowed to move. This is the single largest "
                                       "fixed overhead in the cycle after the Z travel itself, "
                                       "and Section 5.2.1 measures it at 0.93 s for an open and 0.95 s "
                                       "for a close including the phase pause."),
    ])
    rep.p(
        "Grip force is set purely by the closed angle, which was tuned on the rig until the jaws "
        "held a block without marking it. Over the sixteen logged hardware builds and the "
        "commissioning runs that preceded them, **no block was dropped**, crushed or lost from "
        "the claw during a carry. "
        "[[VALUE NEEDED: if you want a number for this in the defence, count the total "
        "pick-and-place attempts made across the project and how many failed at the grip.]]")

    rep.h3("3.2.2 The rotation stepper")
    rep.p(
        "A 28BYJ-48 through a ULN2003 turns the claw a quarter of its 2,048-step output "
        "revolution, 512 steps, at 10 rpm. The four ULN2003 inputs go to Mega pins 38, 36, 39 "
        "and 37, and the stepper library is driven in the IN1/IN3/IN2/IN4 order these boards "
        "actually require and not in pin order.")
    rep.p(
        "The mechanism has neither a home switch nor an angle sensor, so its state is tracked "
        "and not measured. Three things keep that tracking honest:")
    rep.bullets([
        "**The build always returns the claw to neutral over the feeder before it descends** "
        "(phase 3), and again after the block is placed (phase 14). The tracked angle is "
        "never more than one cycle old.",
        "**A manual jog is marked uncalibrated.** `A <degrees>` is a signed relative jog capped "
        "at one turn per command, and an angle that is not exactly 0, +90 or -90 has no "
        "calibrated tool offset, so the `G` command and the grid-mode latches are refused until "
        "a build has returned the claw to neutral.",
        "**Rotation is a property of the grid, not of a block.** The `B` command takes no "
        "rotation word at all. Vertical mode places the block unrotated; horizontal mode turns "
        "it 90 degrees. A fourth word on a `B` command is a parse error whose message names the "
        "mode latch.",
    ])
    rep.p(
        "Rotation repeatability on the rig was good: the quarter turns land consistently and no "
        "cumulative drift was observed across a session. Neutral is re-established between "
        "sessions by the operator physically setting the claw square before power-on, which the "
        "firmware states loudly in its own startup banner because there is no way to verify it "
        "in software. "
        "[[VALUE NEEDED: if you measured the rotation repeatability (e.g. angular error after "
        "N quarter turns), give it here.]]")

    rep.h3("3.2.3 Tool-centre offsets")
    rep.p(
        "The X and Y counters describe the gantry **holder**, not the point where a block is "
        "actually released. The difference is a signed vector from the holder reference to the "
        "block-placement centre, and the firmware subtracts it from the requested cell centre "
        "before moving, so that the tool rather than its holder arrives at the cell:")
    rep.code("holder target = desired block centre  -  tool offset(rotation)")
    rep.defs([
        ("neutral, (0.0, 0.0) cm",
         "A vertical build never turns the claw, so the holder and the block centre coincide. "
         "This zero is genuine, not a placeholder."),
        ("CW (+90 degrees), (+0.9, -0.3) cm",
         "The pickup-rotate swing. The grip point sits about (-0.3, +0.6) cm off the rotation "
         "stepper's axis, so a 90-degree turn carries the block centre round that axis instead "
         "of spinning it in place. This is the only rotation a build ever asks for."),
        ("CCW (-90 degrees), (0.0, 0.0) cm",
         "No grid or build route requests a counter-clockwise placement, so this has never been "
         "measured. It is kept at zero, and kept in the list at all, because the offset lookup "
         "is written over all three rotation states."),
    ])
    rep.p(
        "The CW pair was derived from a rig measurement rather than from a drawing: a horizontal "
        "placement was landing 1.4 cm too far from the X home switch with Y dead on, and "
        "(+0.9, -0.3) is the unique swing that fits those two readings once the wrongly-signed "
        "grid offset it had been hiding behind was removed. Section 5.7 tells that story properly, "
        "because it is the clearest example in the project of a correction applied to the wrong "
        "quantity.")

    # ------------------------------------------------------------------
    rep.h2("3.3 Processing and Control Hardware")
    rep.defs([
        ("Raspberry Pi 5", "8 GB of RAM, a Debian-based operating system and its own USB-C "
                           "supply. It owns camera capture through Picamera2, the whole vision "
                           "pipeline, the FastAPI service and its WebSocket event stream, the "
                           "browser application it serves, both serial clients, the two-board "
                           "orchestrator, and every safety gate and session lock in the system."),
        ("Arduino MEGA 2560", "An ATmega2560 with 8 KB of SRAM and 256 KB of flash, on USB "
                              "serial at 9600. It owns X/Y/Z step generation and direction, "
                              "homing, the hardware and software limits, the grid-to-steps "
                              "arithmetic, the gripper servo, the rotation stepper, the "
                              "fourteen-phase build cycle and the acknowledgement protocol."),
        ("Arduino Uno", "An ATmega328P with 2 KB of SRAM and 32 KB of flash, on its own USB "
                        "serial link at 9600. It owns the feed state machine, the container and "
                        "alignment servos, the belt driver, exit HC-SR04, stage IR sensor and the "
                        "correlated protocol-2 serial interface."),
    ])

    rep.h3("3.3.1 Why a MEGA for the gantry")
    rep.p(
        "The gantry controller is a MEGA rather than an Uno or a Nano for the plainest of "
        "reasons: **pin count**. The gantry alone needs three step-and-direction pairs and two "
        "driver enable lines (eight pins), four limit switches, one servo channel and four "
        "ULN2003 lines for the rotation stepper. That is seventeen I/O lines before anything is "
        "added, against fourteen digital pins on an Uno, and it leaves nothing for the "
        "commissioning headers and spare lines that a machine under construction genuinely "
        "needs. A MEGA has 54.")
    rep.p(
        "Memory turned out to matter as well, though it was not the reason for the choice. The "
        "sketch prints a long human-readable banner, a full machine report, a grid map and a "
        "calibration table, and on AVR every plain string literal handed to `Serial.print()` is "
        "copied into SRAM at boot. Written the naive way this sketch needed 9,443 bytes of SRAM, "
        "which is 115 % of the MEGA's 8 KB, on a board with four times an Uno's memory. Wrapping every "
        "literal in `F()` moved them into flash:")
    rep.table(
        "Gantry firmware resource usage, before and after `F()`.",
        ["Resource", "Naive", "With `F()`", "Capacity"],
        [
            ["SRAM", "9,443 bytes (115 %)", "2,099 bytes (26 %)", "8 KB"],
            ["Flash", "39,158 bytes (15 %)", "40,590 bytes (15 %)", "256 KB"],
        ],
        widths=[3.4, 4.0, 4.0, 3.2], size=9)
    rep.p(
        "That measurement is why the serial protocol looks the way it does. Space-separated "
        "`key=value` fields with no JSON, no braces and no quotes are not a stylistic choice: "
        "on an 8 KB AVR at 9600 baud, braces and quotes cost SRAM and airtime for nothing.")

    # ------------------------------------------------------------------
    rep.h2("3.4 Vision System")

    rep.h3("3.4.1 Camera hardware and mounting")
    rep.defs([
        ("Camera", "A DORHEA Raspberry Pi camera module: OV5647 sensor, 5 MP, with a 160-degree "
                   "fisheye lens, connected to the Pi 5 over the CSI ribbon."),
        ("Capture", "1296 x 972 through Picamera2, which is the binned full-field-of-view sensor "
                    "mode. Capturing binned instead of full resolution keeps the whole "
                    "workspace in frame and keeps the per-frame processing cost inside the "
                    "console's budget."),
        ("Mounting", "Rigidly fixed, pointing straight down, approximately 50 cm above the build "
                     "surface, on a purpose-built wooden support structure that spans the rig "
                     "like a ceiling. Nothing about the mount is adjustable in normal use, which "
                     "matters: every saved calibration embeds the camera's projection identity "
                     "and is refused by every consumer if the lens, orientation or framing has "
                     "changed since."),
    ])
    rep.p(
        "A 160-degree lens at 50 cm is what makes a 23 x 38 cm workspace fit in one frame from a "
        "structure that can actually be built out of timber over a table. The cost is severe "
        "barrel distortion and a strong colour cast, and the next two sections are what those "
        "cost in software.")
    rep.figure("A raw frame straight off the camera, before any correction. The barrel "
               "distortion is visible in the aluminium rails, which are straight on the machine "
               "and curved in the image, and the magenta cast is the uncorrected colour response "
               "described in Section 3.4.3.",
               image="fig-raw-fisheye.png", width_cm=14.0)
    rep.figure("The camera on its wooden support structure, looking straight down at the build "
               "surface from approximately 50 cm.",
               placeholder="Photograph of the overhead camera mount, ideally showing the whole "
                           "rig underneath it so the working distance is visible.")

    rep.h3("3.4.2 Lens correction")
    rep.p(
        "The fisheye is corrected by an equidistant projection model with polynomial radial "
        "terms, tangential terms and independent focal scales, all applied through a remap table "
        "built once at startup. The parameters actually in use on the delivered machine are:")
    rep.table(
        "Lens correction parameters in `camera_settings.json`.",
        ["Parameter", "Value", "Note"],
        [
            ["`lens_fov_deg`", "168.0", "Diagonal reference. Tuned up from the advertised 160."],
            ["`model`", "equidistant", "The source-radius model."],
            ["`k1`, `k2`, `k3`, `k4`", "0.14, 0.18, 0.035, 0.0", "Radial terms."],
            ["`p1`, `p2`", "-0.028, 0.0", "Tangential terms."],
            ["`focal_x_scale`, `focal_y_scale`", "1.2, 1.0", "Independent axis scaling."],
            ["`skew`", "0.020", "Small residual skew."],
            ["`output_fov_deg`", "120.0", "The corrected output field of view."],
            ["`source`", "**estimated**", "Not a checkerboard calibration."],
        ],
        widths=[4.6, 3.6, 6.8], size=9)
    rep.note(
        "**This is a tuned model, not a calibrated one.** The `source` field says `estimated` "
        "and it is telling the truth: the parameters were adjusted by eye against straight edges "
        "in the scene until the image looked straight, using a side-by-side raw/corrected view "
        "with an 8 x 8 straightness ruler drawn on each half. That makes the image good enough "
        "for grid detection and visibly straight, and it does **not** make it "
        "measurement-grade. A flat checkerboard or ChArUco calibration photographed at several "
        "positions and angles is the correct way to finish this, and it is the first item in "
        "the vision half of the future work.")

    rep.h3("3.4.3 Colour correction")
    rep.p(
        "The rig's camera has a colour cast strong enough to be a functional fault rather than a "
        "cosmetic one. The first live frame taken of the printed calibration sheet detected "
        "**nothing at all**, and the reason is worth recording because it was invisible from the "
        "outside:")
    rep.table(
        "Measured on the first live frame: what the camera's white balance did to the scene.",
        ["Surface", "HSV, raw", "HSV, after white balance"],
        [
            ["Green ink on the sheet", "(120, 49, 168)", "(101, 48, 160)"],
            ["Magenta ink on the sheet", "(153, 97, 160)", "(155, 75, 153)"],
            ["White paper", "(137, 37, 195)", "(98, 15, 186)"],
            ["The wall behind the rig", "(139, 78, 176)", "(135, 53, 168)"],
        ],
        widths=[6.0, 4.5, 4.5], size=9)
    rep.p(
        "The green ink had moved to hue 120, which is cyan and not green, with a saturation of "
        "49. It missed the green hue window and fell under the saturation floor at the same "
        "time, so half of every sheet was simply not in the image as far as the detector was "
        "concerned. The pink wall behind the rig, at saturation 78, landed **inside** the "
        "magenta window, so the frame was full of what looked like ink, none of it on the sheet. "
        "That same cast degrades the block detector, which keys on red-minus-blue.")
    rep.p(
        "Two corrections answer it, at two different levels. The sheet detector normalises every "
        "frame internally with a white-patch balance that scales each channel so the frame's "
        "92nd-percentile brightness is neutral; it costs about 3 ms on a 1296 x 972 frame "
        "because it is a lookup table and not a float pass, and it no-ops on a frame that is "
        "already neutral. Above that, a saved colour transform is applied **once, at the "
        "captured frame**, immediately after frame orientation and before every detector, so "
        "that every tool in the system sees the same pixels. That transform is a 3 x 4 "
        "gain-plus-offset matrix with a saturation term, fitted by matching a camera frame "
        "against a phone photograph of the same scene; the fitted profile reached a similarity "
        "of **0.669** against a baseline of 0.404, short of its 0.95 target, and it is "
        "deliberately softened to 76 % strength to stop the offsets crushing the shadows.")
    rep.p(
        "Colour is explicitly **not** part of the saved projection identity, because recolouring "
        "changes no geometry and must not invalidate a saved calibration.")

    rep.h3("3.4.4 Calibration approach")
    rep.p(
        "Calibration here means establishing where the machine's grid sits on the camera image, "
        "which is a different question from correcting the lens. The result of a calibration is "
        "a saved `workspace_map.json` holding four workspace-envelope corners in normalised "
        "image coordinates, the physical grid geometry it was fitted against, and the camera "
        "projection identity it is only valid for. Three routes exist and all three write the "
        "identical artefact, so nothing downstream needs to know which one was used.")
    rep.p("Three routes exist, and all three write the identical artefact:")
    rep.defs([
        ("Four clicked corners",
         "The operator clicks the four corners of the holder envelope on the live image and the "
         "corners are saved directly. Built, and the fastest to run; this is the fallback."),
        ("Printed colour target",
         "An A2 sheet carrying an 8 x 10 lattice of chromatic fiducials is laid on the surface "
         "with its lower-left corner on holder home. The detector segments the ink, assigns "
         "integer lattice indices by breadth-first walks, fits a homography from indices to cell "
         "centres, and re-scores every cell against the footprint that fit predicts for it. "
         "**This is the primary route, and the one presented here.**"),
        ("Evidence-assisted printed target",
         "The same sheet, but pooling accepted observations across several manually confirmed "
         "frames, so that cells hidden by the gantry in one frame can be measured in another. "
         "Built, for when the gantry occludes part of the sheet."),
        ("Placed-block self-calibration",
         "The rig places its own blocks on commanded cells and the calibration is fitted to "
         "where they actually landed, so the thing measured is the thing being calibrated. "
         "Built, and the route with the strongest measured evidence (Section 5.4.2)."),
    ])
    rep.figure("The printed A2 calibration target: an 8 x 10 lattice of green and magenta "
               "fiducial bars, printed at the rig's own cell geometry.",
               image="fig-combined-target.png", width_cm=15.0)
    rep.figure("A detail of the same target. Each 6.0 cm chromatic bar reads as "
               "muted-dark-muted along X and is one vertical fiducial; the perpendicular 2.2 cm "
               "lanes read colour-beige-opposite colour and are the horizontal fiducials.",
               image="fig-target-detail.png", width_cm=13.0)
    rep.p(
        "The physical sheet is A2 landscape, 59.4 x 42.0 cm, with 6.0 x 2.2 cm fiducial bars, "
        "0.8 cm gaps along X and 1.6 cm gaps along Y, the lattice starting 0.8 cm from the page "
        "left and 4.8 cm from the page bottom. It is deliberately printed **larger** than the "
        "machine's grid so that it stays usable at any camera height without reprinting, which "
        "is also why choosing which mode-sized window of it to calibrate on is half the problem: "
        "the detector retains every strongly supported 7 x 6 or 3 x 10 window it finds, orders "
        "them by distance from the image's bottom-left corner, and the operator selects one "
        "before saving. A window needs at least 95 % physical coverage with every row and column "
        "supported, and the fit is gated on colour parity, measured aspect ratio, mean residual "
        "and maximum residual as hard acceptance conditions rather than as reported statistics.")
    rep.p(
        "The sheet must be printed at 100 % scale, never 'fit to page', and laid so that the "
        "centre of its [0,0] block sits on the holder home point. Half of that block then hangs "
        "back past the switches, which is expected: the machine's own lattice is anchored the "
        "same way.")

    # ------------------------------------------------------------------
    rep.h2("3.5 Sensors and Feedback")
    rep.p(
        "The complete sensor inventory of this machine is short, and its shortness is the point: "
        "everything the system knows about its own physical state comes from seven devices.")
    rep.table(
        "Sensor inventory.",
        ["Sensor", "Qty", "Where", "What it establishes", "Signal"],
        [
            ["Micro limit switch", "4",
             "X+ end (pin 30), Y- end (pin 31), Z bottom (pin 28), Z top (pin 29)",
             "The machine's origin, and the physical ends of Z travel. Three of them define a "
             "zero; the Z top one is a stop only.",
             "NC contact to an internal pull-up, confirmed for 200 us before it is believed"],
            ["HC-SR04 ultrasonic", "1", "Feeder container exit (TRIG 4, ECHO 5)",
             "That exactly one block has physically left the hopper onto the belt.",
             "Trigger pulse and echo width, 30 ms timeout, detection below 10.0 cm"],
            ["IR obstacle sensor", "1", "Feeder pickup point (OUT 8)",
             "That a block has arrived at the pickup point, and, read again after the aligner "
             "moves, that it is still there.",
             "Digital presence, active-low by default"],
            ["Overhead camera", "1", "Approximately 50 cm above the build surface",
             "Which blocks are on the surface, where, and what colour.",
             "1296 x 972 frames over CSI through Picamera2"],
        ],
        widths=[3.0, 1.0, 3.6, 4.6, 3.6], size=8.5)
    rep.p(
        "There are **no encoders anywhere in the machine**, and no current sensing on any driver. "
        "Every stepper is open-loop, so a mechanical stall produces step pulses that go nowhere "
        "and nothing reports it. The only thing that keeps position honest is the re-home before "
        "every move, and the only thing that would catch a stall is the camera noticing the "
        "block did not arrive, which is designed but not implemented (Section 5.7.2).")

    rep.h3("3.5.1 Feeder sensor acquisition")
    rep.p(
        "The exit HC-SR04 is read by the standard method: hold the trigger low, pulse it high for "
        "10 us, then measure the echo pulse width with a 30 ms timeout and convert at 343 m/s.")
    rep.code(
        "duration    = pulseIn(echoPin, HIGH, 30000);   // us, 0 on timeout\n"
        "distance_cm = duration == 0 ? -1.0\n"
        "                            : duration * 0.0343f / 2.0f;\n"
        "detected    = distance_cm >= 0.0f\n"
        "           && distance_cm < DETECT_DISTANCE_CM;   // 10.0 cm")
    rep.p(
        "Two details in that path are deliberate. A timeout returns -1 and is reported on the wire as "
        "`distance_cm=no_echo`, which is **never** treated as a detection: 'I heard nothing' and "
        "'nothing is there' are different statements and collapsing them is how a feeder decides "
        "an empty belt is fine. The stage sensor is instead read as a digital presence signal; "
        "`STAGE_IR_DETECTED_LEVEL` records whether the installed module is active-low or active-high. "
        "The sensors are sampled every 100 ms only while a feed cycle is actually running, with "
        "structured readings reported at admission, detection and verification rather than continuously.")
    rep.p(
        "The 10 cm threshold applies only to the exit ultrasonic sensor. The stage IR module's "
        "sensitivity and active level must be commissioned at the pickup fixture. "
        "[[VALUE NEEDED: measured exit distances, stage-IR false-positive/negative observations, "
        "and the number of complete feed cycles verified on the current sensor pair.]]")

    rep.h3("3.5.2 Limit switch acquisition")
    rep.p(
        "All four switches are normally closed to an internal pull-up, so a broken wire reads as "
        "a permanently tripped switch and stops the axis rather than letting it run into its "
        "end. A switch is polled on every single step and must read active continuously for "
        "200 us before the firmware believes it, which is enough to reject contact bounce "
        "without adding a measurable delay to a 1.15 ms step. Trips are edge-counted per switch "
        "and not per axis, so that 'the Z switch was hit' is never an ambiguous statement, "
        "and the counts appear in the machine's full report.")

    # ------------------------------------------------------------------
    rep.h2("3.6 Power and Safety")

    rep.h3("3.6.1 Power")
    rep.p(
        "The power architecture is described in Section 2.5.1: a 12 V / 15 A supply feeding the four "
        "stepper drivers directly, an LM2596 buck converter producing a 5 V rail for the three "
        "servos, the 28BYJ-48 through its ULN2003, both feeder sensors and the A4988's "
        "logic supply, both Arduinos powered over USB from the Pi, the Pi on its own official "
        "supply, and one common ground across all of it.")
    rep.p(
        "The 15 A rating leaves the machine with comfortable headroom, because the four NEMA17 "
        "axes never all move at once: the build cycle moves Z, then X and Y, then Z again, and "
        "the feeder belt runs only while the gantry is idle. Even three axes simultaneously "
        "energised at a typical 1.5 A per phase is a small fraction of the supply. On a "
        "brown-out the failure mode would be a driver losing steps or an Arduino resetting "
        "mid-motion, and the second of those is detected: an unexpected `@0 BOOT` line during a "
        "session is treated as a hard error, because the claw may be holding a block.")

    rep.h3("3.6.2 Safety mechanisms that exist")
    rep.numbered([
        "**Hardware limit switches on every axis end that has one**: X home, Y home, Z bottom "
        "and Z top, all polled on every step and all able to stop a move.",
        "**Software limits on the two ends that have no switch**, X- and Y+, checked before "
        "every move and not during it, so an out-of-envelope target is refused before "
        "anything turns.",
        "**Pre-motion validation of every build.** The cell range, the grid readiness, the "
        "compensated holder target, both Z switches being enabled, and the Z calibration being "
        "sane are all checked before the machine moves at all; a failure at that stage is "
        "reported as `SAFE`, which means literally nothing moved.",
        "**Two distinct failure kinds, never collapsed into one.** `SAFE` means nothing moved "
        "and a retry is fine. `HELD` means the failure happened part way through, the claw may "
        "still be gripping a block and the position is unknown, and it needs a person. They are "
        "separate message kinds precisely so that Pi-side code **cannot** handle them with a "
        "generic 'if not ok, retry'.",
        "**Session lock on uncertainty.** An abort, a timeout, a board reset or a cable loss "
        "locks the session; every further mutation is refused and the only recovery is a person "
        "plus a service restart.",
        "**The feeder refuses to double-load.** A `FEED` request arriving while the stage sensor "
        "already sees a block is refused outright with `stage_occupied`, before the container "
        "opens.",
        "**One command at a time**, enforced at five independent layers from the HTTP route down "
        "to the serial client (Section 4.4.3).",
        "**Cell [0,0] is never a build target**, refused in the firmware, on the Pi and in the "
        "browser.",
    ])

    rep.h3("3.6.3 Safety mechanisms that do not exist")
    rep.p(
        "These are stated plainly, because a report that implies otherwise would be describing a "
        "different machine:")
    rep.bullets([
        "**No hardwired emergency stop.** There is no button, no safety relay, no contactor and "
        "no externally interruptible enable chain that removes hazardous motion energy "
        "independently of the software. The stop of last resort is removing power at the supply, "
        "which is not the same thing as a designed safe power-removal circuit.",
        "**No way to interrupt a motion in progress from software.** The gantry firmware does "
        "not read serial inside its build cycle. Browser 'stop' is stop-after-the-current-block "
        "and the interface says so in those words.",
        "**No watchdog or heartbeat.** If the Pi crashes, the browser closes or the USB cable is "
        "pulled mid-motion, the Mega finishes the command it already received. Nothing tells it "
        "the master is gone.",
        "**No cover or interlock.** The gantry envelope is open.",
        "**No electrical protection fitted.** No fuse in the 12 V line, no reverse-polarity "
        "protection, no flyback diodes on the servo rail, beyond the decoupling around the "
        "A4988.",
        "**No stall detection.** Open-loop steppers with no encoders and no current sensing "
        "cannot report a stall.",
    ])
    rep.p(
        "The operational answer to all of the above is the same, and it is a procedure rather than a mechanism: **the machine is run attended**, with a person present who keeps "
        "clear of the gantry envelope while it is powered and who can pull the supply. The "
        "browser interface deliberately offers no cancel and no retry button, because a control "
        "that implies the machine can be stopped is a lie about the hardware. Fitting a proper "
        "emergency-stop path is the first item of future work in Section 6.2.")

    # ------------------------------------------------------------------
    rep.h2("3.7 System Integration")
    rep.p(
        "In the finished machine the electronics sit off the moving gantry entirely. The four "
        "stepper drivers and the buck converter are mounted on the frame beside the 12 V supply, "
        "with the two Arduinos alongside them; only the motors, the switches, the servo and the "
        "rotation stepper have wiring that travels with the carriage. The Raspberry Pi sits "
        "beside the rig with two USB leads running to the two Arduinos and the camera ribbon "
        "running up to the overhead mount.")
    rep.p("The three integration rules that make the assembly work are:")
    rep.numbered([
        "**Each board is addressed by a stable device path, never by enumeration order.** A Mega "
        "enumerates as `/dev/ttyACM0` and a clone as `/dev/ttyUSB0`, and which board gets which "
        "number depends on plug order. The configuration names each board's "
        "`/dev/serial/by-id/...` path instead, and the service refuses to start if the two "
        "entries name the same device.",
        "**Each board's identity is validated on connect.** The Uno must announce "
        "`@0 READY firmware=belt_v1 protocol=2 board=uno` and it is matched field by field "
        "against the configuration; a mismatch closes the port and fails startup rather than "
        "proceeding with the wrong firmware. The Mega's handshake waits for its own "
        "`@0 READY grid=... mode=...` sync marker.",
        "**Exactly one process owns each resource.** One camera object, one Mega serial port, "
        "one Uno serial port, all created once by the web service's lifespan. Running a "
        "commissioning script while the service is up will contend for the same board and reset "
        "it, which is documented as an operational rule because there is no OS-level exclusive "
        "lock enforcing it.",
    ])
    rep.figure("Complete wiring diagram: Arduino MEGA 2560 gantry controller, its three TB6600 "
               "drivers, the four limit switches, the gripper servo and the ULN2003 rotation "
               "stepper. Every pin is transcribed from the firmware source.",
               image="fig-wiring-mega.png", width_cm=15.5)
    rep.figure("Complete wiring diagram: Arduino Uno feeder controller, the A4988 belt driver, "
               "the container and alignment servos, exit HC-SR04 and stage IR sensor.",
               image="fig-wiring-uno.png", width_cm=15.5)
    rep.p(
        "The complete pin assignments for both controllers are tabulated in Appendix B, taken "
        "directly from the two firmware sources and not from any documentation of them.")
