import type { Point } from "../types";
export interface ProjectionFixture { cols: number; rows: number; corners: Point[]; image_size: [number, number] }
type Matrix = number[][];
function solve(rows: Matrix, values: number[]): number[] { const a = rows.map((row, i) => [...row, values[i]]); for (let col = 0; col < 8; col++) { let pivot = col; for (let row = col + 1; row < 8; row++) if (Math.abs(a[row][col]) > Math.abs(a[pivot][col])) pivot = row; if (Math.abs(a[pivot][col]) < 1e-12) throw new Error("workspace corners are degenerate"); [a[col], a[pivot]] = [a[pivot], a[col]]; const divisor = a[col][col]; for (let j = col; j <= 8; j++) a[col][j] /= divisor; for (let row = 0; row < 8; row++) if (row !== col) { const factor = a[row][col]; for (let j = col; j <= 8; j++) a[row][j] -= factor * a[col][j]; } } return a.map(row => row[8]); }
function homography(src: Point[], dst: Point[]): Matrix { const rows: Matrix = []; const values: number[] = []; src.forEach(([x, y], i) => { const [u, v] = dst[i]; rows.push([x, y, 1, 0, 0, 0, -u * x, -u * y], [0, 0, 0, x, y, 1, -v * x, -v * y]); values.push(u, v); }); const h = solve(rows, values); return [[h[0], h[1], h[2]], [h[3], h[4], h[5]], [h[6], h[7], 1]]; }
function project(matrix: Matrix, [x, y]: Point): Point { const z = matrix[2][0] * x + matrix[2][1] * y + matrix[2][2]; if (Math.abs(z) < 1e-12) throw new Error("workspace mapping reaches infinity"); return [(matrix[0][0] * x + matrix[0][1] * y + matrix[0][2]) / z, (matrix[1][0] * x + matrix[1][1] * y + matrix[1][2]) / z]; }
export class WorkspaceProjection { readonly cols: number; readonly rows: number; private readonly toMachine: Matrix; private readonly toImage: Matrix; constructor(data: ProjectionFixture) { this.cols = data.cols; this.rows = data.rows; const square: Point[] = [[0, 0], [1, 0], [1, 1], [0, 1]]; this.toMachine = homography(data.corners, square); this.toImage = homography(square, data.corners); }
  normalizedAt(point: Point, imageSize: Point): Point { return project(this.toMachine, [point[0] / imageSize[0], point[1] / imageSize[1]]); }
  cellAt(point: Point, imageSize: Point): Point | null { const [u, v] = this.normalizedAt(point, imageSize); if (u < 0 || v < 0 || u > 1 || v > 1) return null; return [Math.min(Math.floor(u * this.cols), this.cols - 1), Math.min(Math.floor(v * this.rows), this.rows - 1)]; }
  pixelAt(u: number, v: number, imageSize: Point): Point { const point = project(this.toImage, [u, v]); return [point[0] * imageSize[0], point[1] * imageSize[1]]; }
  targetPolygon(col: number, row: number, imageSize: Point): Point[] { return [this.pixelAt(col / this.cols, row / this.rows, imageSize), this.pixelAt((col + 1) / this.cols, row / this.rows, imageSize), this.pixelAt((col + 1) / this.cols, (row + 1) / this.rows, imageSize), this.pixelAt(col / this.cols, (row + 1) / this.rows, imageSize)]; }
}
