import { StrictMode } from "react";
import { createRoot } from "react-dom/client";
import { registerSW } from "virtual:pwa-register";
import { Root } from "./routes/Root";
import "@fontsource/fira-sans/latin-400.css";
import "@fontsource/fira-sans/latin-500.css";
import "@fontsource/fira-sans/latin-600.css";
import "@fontsource-variable/fira-code/wght.css";
import "./style.css";
registerSW({ immediate: false });
createRoot(document.getElementById("root")!).render(<StrictMode><Root /></StrictMode>);
